apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: decapod-db
spec:
  destination:
    namespace: decapod-db
    server: https://kubernetes.default.svc
  project: decapod-controller
  source:
    path: hanu-reference/decapod-controller/postgresql
    repoURL: https://github.com/openinfradev/decapod-manifests.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
